version: "2"

services:
  php:
    image: divante/open-loyalty-fpm
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-group: openloyalty
        awslogs-region: ap-southeast-1
        awslogs-stream-prefix: web
  nginx:
    image: divante/open-loyalty-web
    ports:
      - "80:80"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
  elk:
    image: divante/open-loyalty-elasticsearch:2.2.0
  db:
    image: postgres:9
    env_file:
      - .env
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
